apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: minio
  namespace: minio
spec:
  replicas: 1
  selector:
    matchLabels:
      name: minio
  template:
    metadata:
      name: minio
      labels:
        name: minio
    spec:
      containers:
        - name: minio
          image: minio/minio
          args:
            - server
            - /data
            - --console-address
            - ":9001"
          env:
            - name: MINIO_ROOT_USER
              value: xusenhao
            - name: MINIO_ROOT_PASSWORD
              value: xu20001123
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: minio-data
              mountPath: /data
      volumes:
        - name: minio-data
          hostPath:
            path: /data/minio-data
            type: DirectoryOrCreate
  serviceName: minio
---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: minio
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      nodePort: 30090
      name: minio-9000
    - port: 9001
      targetPort: 9001
      nodePort: 30091
      name: minio-9001
  selector:
    name: minio