apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: rabbitmq
spec:
  serviceName: rabbitmq
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
        - env:
            - name: RABBITMQ_DEFAULT_USER
              value: "root"
            - name: RABBITMQ_DEFAULT_PASS
              value: "123456"
          image: rabbitmq:management
          imagePullPolicy: IfNotPresent
          name: rabbitmq
          ports:
            - containerPort: 15672
              name: manager
            - containerPort: 5672
              name: broker
---
apiVersion: v1
kind: List
items:
  - apiVersion: v1
    kind: Service
    metadata:
      name: mqadmin
    spec:
      ports:
        - name: http
          port: 15672
          protocol: TCP
          targetPort: 15672
      selector:
        app: rabbitmq
  - apiVersion: v1
    kind: Service
    metadata:
      name: rabbitmq
    spec:
      ports:
        - name: http
          port: 5672
          protocol: TCP
          targetPort: 5672
      selector:
        app: rabbitmq
