apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: rabbit-cluster
  namespace: pie-engine-infra
spec:
  replicas: 3
  rabbitmq:
    additionalConfig: |
      default_user=guest
      default_pass=guest
  persistence:
    storageClassName: basic-13000-share-sc
    storage: 300Gi
  resources:
    requests:
      cpu: 4000m
      memory: 16Gi
    limits:
      cpu: 8000m
      memory: 32Gi
