apiVersion: redis.kun/v1alpha1
kind: DistributedRedisCluster
metadata:
  annotations:
    redis.kun/scope: cluster-scoped
  name: redis-cluster
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node
            operator: In
            values:
            - "redis"
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - podAffinityTerm:
            labelSelector:
              matchExpressions:
              - key: node
                operator: In
                values:
                - redis
            topologyKey: kubernetes.io/hostname
          weight: 100
  image: pie-engine-infra/redis:5.0
  masterSize: 6
  clusterReplicas: 1
  resources:
    limits:
      cpu: 2000m
      memory: 8000Mi
    requests:
      cpu: 1000m
      memory: 4000Mi
  storage:
    type: persistent-claim
    size: 300Gi
    class: basic-13000-share-sc
    deleteClaim: true
  config:
    activerehashing: "yes"
    appendfsync: everysec
    appendonly: "yes"
    maxclients: "10000"
    hash-max-ziplist-entries: "512"
    hash-max-ziplist-value: "64"
    hll-sparse-max-bytes: "3000"
    list-compress-depth: "0"
    maxmemory-policy: noeviction
    maxmemory-samples: "5"
    no-appendfsync-on-rewrite: "no"
    notify-keyspace-events: ""
    set-max-intset-entries: "512"
    slowlog-log-slower-than: "10000"
    slowlog-max-len: "128"
    stop-writes-on-bgsave-error: "yes"
    tcp-keepalive: "60"
    timeout: "60"
    zset-max-ziplist-entries: "128"
    zset-max-ziplist-value: "64"
