apiVersion: "zookeeper.pravega.io/v1beta1"
kind: "ZookeeperCluster"
metadata:
  name: "zookeeper-cluster"
  namespace: pie-engine-infra
spec:
  replicas: 6
  storageType: persistence
  persistence:
    reclaimPolicy: Delete
    spec:
      storageClassName: "basic-13000-share-sc"
      resources:
        requests:
          storage: 300Gi
  image:
    repository: 10.0.4.5:1180/pie-engine-infra/pravega/zookeeper
    tag: 0.2.10
  pod:
    #image: 10.0.4.5:1180/pie-engine-infra/pravega/zookeeper:0.2.10
    nodeSelector:
      node: "zookeeper"
    resources:
      requests:
        cpu: 2000m
        memory: 8Gi
      limits:
        cpu: 4000m
        memory: 8Gi
