apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka-deploy
  labels:
    name: kafka-deploy
spec:
  serviceName: kafka
  replicas: 1
  selector:
    matchLabels:
      name: kafka-pod
  template:
    metadata:
      labels:
        name: kafka-pod
    spec:
      terminationGracePeriodSeconds: 30  #k8s正确、优雅地关闭应用，等待时间30秒
      #nodeSelector:
      # kafka: "true"
      hostname: kafka-hostname       #设置pod的hostaname
      containers:
        - name: "kafka"
          image: wurstmeister/kafka:2.13-2.8.1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9092
          env:
            - name: KAFKA_ADVERTISED_PORT
              value: "9092"
            - name: KAFKA_ADVERTISED_HOST_NAME
              value: kafka-service.default
            - name: KAFKA_ZOOKEEPER_CONNECT
              value: zookeeper.default.svc.cluster.local:2181
            - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-service
  labels:
    name: kafka-service
spec:
  selector:
    name: kafka-pod
  # sessionAffinity: ClientIP
  ports:
    - name: "kafka"
      port: 9092
      targetPort: 9092
