apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  labels:
    name: zookeeper
spec:
  serviceName: zookeeper
  replicas: 1
  selector:
    matchLabels:
      name: zookeeper
  template:
    metadata:
      labels:
        name: zookeeper
    spec:
      terminationGracePeriodSeconds: 30  #k8s正确、优雅地关闭应用，等待时间30秒
      containers:
        - name: zookeeper
          image: zookeeper
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 2181
          volumeMounts:
            - name: zk-data
              readOnly: false
              mountPath: /opt/zookeeper/data
      volumes:
        - name: zk-data
          hostPath:
            path: /data/zookeeper
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  labels:
    name: zookeeper
spec:
  selector:
    name: zookeeper
  ports:
    - name: zookeeper
      port: 2181
      targetPort: 2181

